version: "3.1"

services:
  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - .config:/etc/mysql/conf.d/
      - .data:/var/lib/mysql/
      - .log:/var/log/mysql/
    environment:
      MARIADB_ROOT_PASSWORD: zhuCong

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
